### ISSUE TITLE
Unable to pull demo-datagen

### ISSUE THREAD

**Issue by CAJan93** [risingwavelabs/risingwave-demo#27]
Hi, I am unable to pull the `demo-datagen` image

```sh 
docker pull  ghcr.io/risingwavelabs/demo-datagen:v1.0.6
v1.0.6: Pulling from risingwavelabs/demo-datagen
3b65ec22a9e9: Pulling fs layer 
4c992fb70601: Pulling fs layer 
error pulling image configuration: download failed after attempts=1: unknown blob
```

This image is used in the cdn-metrics example (see [docker-compose.yaml](https://github.com/risingwavelabs/risingwave-demo/blob/d6aa0e06d3bf93f87571559efd4ccd87ab2081f0/cdn-metrics/docker-compose.yml#L316))

**Comment by TennyZhuang** [comment]
@neverchanje can you sync the image?

**Comment by neverchanje** [comment]
Thank you for reporting this problem. I think it's due to a migration of repo. Now I have upgraded the docker image and please `git pull origin main` and try again!

**Comment by CAJan93** [comment]
Issue is resolved by https://github.com/risingwavelabs/risingwave-demo/pull/29 Thank you very much for your help @neverchanje
